name: Deploy HML-Miguilim

on:
  workflow_dispatch:

env:
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  SMTP_HOST_IP: ${{ secrets.SMTP_HOST_IP }}
  ENVIRONMENT: HML
  DSPACE_URL: https://homologacaomiguilim.ibict.br
  INDICADORES_URL: https://indicadoreshomologacaomiguilim.ibict.br

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64, runner-hml]
    environment:
      name: HML
      url: 'http://172.16.21.20'

    steps:
      - uses: actions/checkout@v3
      - run: |
          sh docker/dspace/build-dspace.sh 
