name: Pipeline - Deploy Miguilim

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  SMTP_HOST_IP: ${{ secrets.SMTP_HOST_IP }}

jobs:
  PRD:
    runs-on: [self-hosted, linux, x64, runner-prd]
    env:
      ENVIRONMENT: PRD
      DSPACE_URL: https://miguilim.ibict.br
      INDICADORES_URL: https://indicadoresmiguilim.ibict.br/indicadores-miguilim
    environment: 
      name: PRD
      url: 'https://miguilim.ibict.br/'

    steps:
      - uses: actions/checkout@v3
      - run: |
          sh docker/dspace/build-dspace.sh
